### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by cblair91** [cblair91/GriefPrevention#1]
- [ ] Move commands from main class to own classes
- [ ] Clean up unused events (Check with @Slind14)
- [ ] Fix wither dupe (wither skull/wither spawn detection)
- [ ] Improve speed performance
- [ ] Clean up enums (enums use capitalized cases)
- [ ] Try to merge some classes together (common code base / not needed)
